[build]
  functions = "functions"

[functions]
  included_files = ["data/**"]
  node_bundler = "esbuild"
  external_node_modules = ["hnswlib-node"]

[[redirects]]
  from = "/"
  to = "/.netlify/functions/index"
  status = 200
